version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/pmtool
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=change_me
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
